trigger:
  - main

pool:
  name: "quiz_a_p"

steps:
  - task: UseNode@2
    inputs:
      versionSpec: "18.x"
      addToPath: true

  - script: |
      npm install  # You can use 'yarn install' if you're using Yarn instead of npm
    displayName: "Install dependencies"

  - script: |
      npm run build  # Replace with 'yarn build' if you're using Yarn
    displayName: "Build project"

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: "drop"
      publishLocation: "Container"
